-- Auto-generated by rails_like_codegen (Jinja)
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS orgs (
  id BIGSERIAL PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name varchar(40));

DROP TRIGGER IF EXISTS trg_set_updated_at_orgs ON orgs;
CREATE TRIGGER trg_set_updated_at_orgs
BEFORE UPDATE ON orgs
FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

-- Foreign keys, indexes, join tables
