clusterId: nothing
mode: isolated

remoteHourlyUploads: disabled

server:
  tomcat:
    max-threads: 512
  port: 9000

admissionWindowHrs: 24

node:
  user_defined_id: test-node-0

aws:
  region: eu-west-2

dir:
  checkpointDir: ${user.home}/.okapi/hourly-checkpoints
  shardCheckpointRoot: ${user.home}/.okapi/shard-checkpoints
  parquetRoot: ${user.home}/.okapi/parquet-checkpoints
  shardAssetsRoot: ${user.home}/.okapi/shard-assets

checkpoint:
  gapMillis: 3600000
  dir: ${user.home}/.okapi/periodic-checkpoints

backgroundThreads: 10

zk:
  connectionString: localhost:2181
  backoffBase: 2000
  backoffNRetries: 2
  node:
    type: metrics-processor

dataBucket: okapi-test-data-bucket
remoteCkptDelaySeconds: 500
rocksBacklog: 100000
rocksDir: ${user.home}/.okapi/rocks-dbs
writeBack:
  millis: 1000