openapi: 3.0.3
info:
  title: okapi API
  version: 1

paths:
  /api/1/orgs:
    get:
      summary: List orgs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Orgs'
    post:
      summary: Create Orgs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Orgs'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orgs'

  /api/1/orgs/{id}:
    get:
      summary: Get Orgs by id
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer, format: int64 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orgs'
        '404':
          description: Not found
    post:
      summary: Update Orgs
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer, format: int64 }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Orgs'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orgs'
        '404':
          description: Not found

components:
  schemas:
    Orgs:
      type: object
      properties:
        id:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        name:
          type: string