package org.okapi.rest.chat;

public enum CHAT_RESPONSE_TYPE {
  MARKDOWN_TEXT,
  PLOT_CMD,
  GET_TRACES_CMD,
  THOUGHT,
  PLAN,
  RESPONSE,
  GET_TRACE_FOLLOW_UP,
  PLOT_METRIC_FOLLOW_UP,
  TOOL_CALL_REQUEST,
  TOOL_CALL_RESPONSE
}
