apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:2.3
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: s3
            - name: DEBUG
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  selector:
    app: localstack
  ports:
    - name: s3
      port: 4566
      targetPort: 4566
      protocol: TCP
  type: ClusterIP