# nginx-conf.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: okapi
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      # quick landing ping
      location = / {
        return 200 'ok';
        add_header Content-Type text/plain;
      }

      # Forward /okapi/* to the service, strip the /okapi/ prefix
      location /okapi/ {
        proxy_pass http://okapi-logs-svc.okapi.svc.cluster.local:8080/;  # trailing / strips prefix
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;
      }    
    }
---
# nginx-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: okapi
  labels: { app: nginx }
spec:
  replicas: 1
  selector:
    matchLabels: { app: nginx }
  template:
    metadata:
      labels: { app: nginx }
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          readinessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: okapi
  labels:
    app: nginx
spec:
  type: LoadBalancer                # MetalLB will assign an IP
  selector:
    app: nginx                      # Must match labels on your nginx pods
  ports:
    - name: http
      port: 80                        # Port exposed by the service
      targetPort: 80                  # Port your nginx container listens on