apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: okapi-pod-reader
  namespace: okapi
rules:
  - apiGroups: [ "" ]
    resources: [ "pods","endpoints","services" ]
    verbs: [ "get","list","watch" ]
  - apiGroups: [ "discovery.k8s.io" ]
    resources: [ "endpointslices" ]
    verbs: [ "get","list","watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: okapi-pod-reader-binding
  namespace: okapi
subjects:
  - kind: ServiceAccount
    name: default
    namespace: okapi
roleRef:
  kind: Role
  name: okapi-pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: okapi-logs
  labels:
    app: okapi-logs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: okapi-logs
  template:
    metadata:
      labels:
        app: okapi-logs
        okapi_service: okapi-logs
    spec:
      containers:
        - name: okapi-logs
          image: okapi-logs:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SERVER_PORT
              value: "8080"
            # Enable S3 against in‑cluster Localstack
            - name: OKAPI_LOGS_S3_BUCKET
              value: okapi-e2e
            - name: OKAPI_LOGS_S3_BASEPREFIX
              value: logs
            - name: OKAPI_LOGS_S3_REGION
              value: us-east-1
            - name: OKAPI_LOGS_S3_ENDPOINT
              value: http://localstack.okapi:4566
            # Localstack accepts any credentials but AWS SDK requires them
            - name: AWS_ACCESS_KEY_ID
              value: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              value: secretKey
            # SWIM k8s discovery: select pods via this label value
            - name: OKAPI_SWIM_K8S_OKAPI-SERVICE-LABEL-VALUE
              value: okapi-logs
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: okapi-logs-svc
  labels:
    app: okapi-logs
spec:
  selector:
    app: okapi-logs
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080