clusterId: a11a911a0282b64db1f6b8aa89bbcc2b
orgId: test-org
server:
  port: 9001

zk:
  connectionString: localhost:2181
  backoffBase: 2000
  backoffNRetries: 2


dataBucket: okapi-test-data-bucket
pageSize: 16384 # 16kB pages
maxCachedPages: 2000
lifeTimeMinutes: 5
cacheExpiryMillis: 10000

google:
  clientId: none


cookies:
  secureOnly: false
  httpOnly: true