CREATE TABLE IF NOT EXISTS okapi_traces.spans_table_v1 (
    ts_start_ns Int64,
    ts_end_ns Int64,
    span_id String CODEC(ZSTD),
    parent_span_id String CODEC(ZSTD),
    trace_id String CODEC(ZSTD),
    kind LowCardinality(String),
    kind_string String CODEC(ZSTD),
    service_name LowCardinality(String),
    service_peer_name LowCardinality(String),
    http_method LowCardinality(String),
    http_status_code Nullable(Int32),
    http_request_size Nullable(Int32),
    http_response_size Nullable(Int32),
    http_origin String CODEC(ZSTD),
    http_host LowCardinality(String),
    server_address String CODEC(ZSTD),
    server_port Nullable(Int32),
    client_address String CODEC(ZSTD),
    client_port Nullable(Int32),
    source_address String CODEC(ZSTD),
    source_port Nullable(Int32),
    network_protocol_type LowCardinality(String),
    network_protocol_version LowCardinality(String),
    db_system_name LowCardinality(String),
    db_collection_name String CODEC(ZSTD),
    db_namespace LowCardinality(String),
    db_operation_name LowCardinality(String),
    db_response_status_code Int32,
    db_query_text String CODEC(ZSTD),
    db_query_summary String CODEC(ZSTD),
    db_stored_procedure_name String CODEC(ZSTD),
    db_response_returned_rows Int32,
    rpc_method LowCardinality(String),
    rpc_method_original LowCardinality(String),
    rpc_response_status_code Int32,
    attribs_str_0 Map(String, String),
    attribs_str_1 Map(String, String),
    attribs_str_2 Map(String, String),
    attribs_str_3 Map(String, String),
    attribs_str_4 Map(String, String),
    attribs_str_5 Map(String, String),
    attribs_str_6 Map(String, String),
    attribs_str_7 Map(String, String),
    attribs_str_8 Map(String, String),
    attribs_str_9 Map(String, String),
    attribs_number_0 Map(String, Float64),
    attribs_number_1 Map(String, Float64),
    attribs_number_2 Map(String, Float64),
    attribs_number_3 Map(String, Float64),
    attribs_number_4 Map(String, Float64),
    attribs_number_5 Map(String, Float64),
    attribs_number_6 Map(String, Float64),
    attribs_number_7 Map(String, Float64),
    attribs_number_8 Map(String, Float64),
    attribs_number_9 Map(String, Float64)
)
ENGINE = MergeTree
PARTITION BY toStartOfHour(toDateTime(ts_start_ns / 1000000000))
ORDER BY (service_name, trace_id, span_id, ts_start_ns);
