# Sample configuration for okapi-traces module
# Copy or rename to application.yml and adjust as needed.

server:
  port: 8080  # HTTP port for the traces service

spring:
  application:
    name: okapi-traces

# Trace ingestion and storage settings
okapi:
  traces:
    # Local directory where hourly tracefiles are appended.
    # Files are created per tenant/app as: <baseDir>/<tenant>/<application>/tracefile.<hourBucket>.bin
    baseDir: /var/lib/okapi/traces

    # Page flush threshold (estimated serialized bytes). Defaults to ~8MB.
    # When a per-tenant/app page exceeds this size, it is flushed to the tracefile and a new page starts.
    page:
      maxEstimatedBytes: 8388608  # 8 MiB

    # Bloom filter parameters for per-page traceId membership tests.
    # expectedInsertions: estimated number of unique traceIds per page.
    # fpp: target false positive probability (smaller => larger bloom serialized size).
    bloom:
      expectedInsertions: 100000
      fpp: 0.01

    # TraceFileWriter idle-close behavior (milliseconds)
    # Idle streams are auto-closed to avoid excessive open file descriptors.
    writer:
      idleCloseMillis: 60000         # close an idle writer after 60s
      reapIntervalMillis: 15000      # scan for idle streams every 15s

    # Batch upload job cadence (milliseconds). Older-than-1h local tracefiles are uploaded to S3.
    uploadIntervalMs: 600000  # run every 10 minutes

    # Query engine thread pool size. If 0 or omitted, defaults to available processors.
    query:
      threads: 0

    # S3 byte-range cache configuration for the S3QueryProcessor
    s3:
      # Target bucket where tracefiles live (reader) and where uploads go (uploader).
      bucket: okapi-trace-files
      # region
      region: eu-west-2
      # Base key prefix for tracefiles. Effective object keys are: <basePrefix>/<tenant>/<application>/tracefile.<hourBucket>.bin
      basePrefix: okapi
      # Client-side byte-range cache for efficient page reads.
      cache:
        maxPages: 128          # max pages retained in cache
        expirySec: 60          # expire cache entries after this many seconds of inactivity

logging:
  level:
    root: INFO
    org.okapi.traces: INFO  # Increase to DEBUG for verbose IO and upload logs