apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: okapi-clickhouse
  namespace: okapi
spec:
  configuration:
    users:
      default/password: okapi_testing_password
      default/profile: default
      default/quota: default
    clusters:
      - name: okapi
        layout:
          shardsCount: 1
          replicasCount: 2
  templates:
    serviceTemplates:
      - name: okapi-clickhouse-svc
        spec:
          type: ClusterIP
          ports:
            - name: http
              port: 8123
              targetPort: 8123
            - name: tcp
              port: 9000
              targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: okapi-clickhouse
  namespace: okapi
spec:
  type: ClusterIP
  selector:
    clickhouse.altinity.com/chi: okapi-clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: tcp
      port: 9000
      targetPort: 9000
