- type: http
  sourceId: prometheus
  host: "http://localhost:9090"
  headers:
    content-type: application/json

- type: http
  sourceId: jaeger
  host: "http://localhost:16686"
  headers:
    content-type: application/json
