package org.okapi.data.dto;

import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

@AllArgsConstructor
@Builder
@DynamoDbBean
@NoArgsConstructor
public class OrgDtoDdb {
  String orgId;
  String orgName;
  String orgCreator;
  Instant created;

  @DynamoDbPartitionKey
  @DynamoDbAttribute(TableAttributes.ORG_ID)
  public String getOrgId() {
    return orgId;
  }

  public OrgDtoDdb setOrgId(String orgId) {
    this.orgId = orgId;
    return this;
  }

  @DynamoDbAttribute(TableAttributes.ORG_NAME)
  public String getOrgName() {
    return orgName;
  }

  public OrgDtoDdb setOrgName(String orgName) {
    this.orgName = orgName;
    return this;
  }

  @DynamoDbAttribute(TableAttributes.ORG_CREATOR)
  public String getOrgCreator() {
    return orgCreator;
  }

  public OrgDtoDdb setOrgCreator(String orgCreator) {
    this.orgCreator = orgCreator;
    return this;
  }

  @DynamoDbAttribute(TableAttributes.CREATED_TIME)
  @DynamoDbAutoGeneratedTimestampAttribute
  public Instant getCreated() {
    return created;
  }

  public OrgDtoDdb setCreated(Instant created) {
    this.created = created;
    return this;
  }
}
