package org.okapi.data.dto;

import java.time.Instant;
import lombok.*;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

@AllArgsConstructor
@NoArgsConstructor
@Builder
@Getter
@Setter
@DynamoDbBean
public class TeamDtoDdb {
  private String teamId;
  private String orgId;
  private String teamName;
  private String description;
  Instant createdAt;

  @DynamoDbPartitionKey
  @DynamoDbAttribute(TableAttributes.TEAM_ID)
  public String getTeamId() {
    return teamId;
  }

  public TeamDtoDdb setTeamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

  @DynamoDbAttribute(TableAttributes.ORG_ID)
  public String getOrgId() {
    return orgId;
  }

  public TeamDtoDdb setOrgId(String orgId) {
    this.orgId = orgId;
    return this;
  }

  @DynamoDbAttribute(TableAttributes.TEAM_NAME)
  public String getTeamName() {
    return teamName;
  }

  public TeamDtoDdb setTeamName(String teamName) {
    this.teamName = teamName;
    return this;
  }

  @DynamoDbAttribute(TableAttributes.TEAM_DESCRIPTION)
  public String getDescription() {
    return description;
  }

  public TeamDtoDdb setDescription(String description) {
    this.description = description;
    return this;
  }

  @DynamoDbAutoGeneratedTimestampAttribute
  public Instant getCreatedAt() {
    return createdAt;
  }

  public TeamDtoDdb setCreatedAt(Instant createdAt) {
    this.createdAt = createdAt;
    return this;
  }
}
