package org.okapi.data.dto;

import static org.okapi.data.dto.TableAttributes.*;

import java.time.Instant;
import lombok.*;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;

@Builder(toBuilder = true)
@DynamoDbBean
@AllArgsConstructor
@NoArgsConstructor
public class UserRoleRelationDtoDdb {

  String userId;
  String role;
  Instant createdAt;
  UserRoleRelationDto.STATUS status;

  @DynamoDbAttribute(USER_ID)
  @DynamoDbPartitionKey
  public String getUserId() {
    return userId;
  }

  public UserRoleRelationDtoDdb setUserId(String userId) {
    this.userId = userId;
    return this;
  }

  @DynamoDbAttribute(USER_ROLE)
  @DynamoDbSecondaryPartitionKey(indexNames = TablesAndIndexes.ROLE_TO_USER_GSI)
  @DynamoDbSortKey
  public String getRole() {
    return role;
  }

  public UserRoleRelationDtoDdb setRole(String role) {
    this.role = role;
    return this;
  }

  @DynamoDbAttribute(CREATED_TIME)
  @DynamoDbAutoGeneratedTimestampAttribute
  public Instant getCreatedAt() {
    return createdAt;
  }

  public UserRoleRelationDtoDdb setCreatedAt(Instant createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  @DynamoDbAttribute(USER_ROLE_STATUS)
  public UserRoleRelationDto.STATUS getStatus() {
    return status;
  }

  public UserRoleRelationDtoDdb setStatus(UserRoleRelationDto.STATUS status) {
    this.status = status;
    return this;
  }
}
