package org.okapi.metrics.common.pojo;

public enum NodeState {
  SHARD_CHECKPOINTING_START,
  SHARD_CHECKPOINTS_UPLOADED,
  SHARD_CHECKPOINTS_DOWNLOADING,
  SHARD_CHECKPOINTS_APPLIED,
  ROLLED_BACK,
  METRICS_CONSUMPTION_START,
  NODE_CREATED,
  PROCESS_STOPPED
}
