okapi:
  logs:
    s3:
      region: eu-west-2
      uploadGraceMs: 300000 # 5 min grace period
      bucket: test-bucket
      basePrefix: logs
      endpoint: http://localhost:4566
      uploadIntervalMs: 1800000
    dataDir: data-pages
    maxPageBytes: 8388608 # 8 MB by default
    maxDocsPerPage: 1000
    maxPageWindowMs: 3600000 # 1hr
    idxExpiryDuration: 3600000 # 1hr expiry duration for an index file
  swim:
    svcName: logs
    s3:
      bucket: test-bucket