server:
  port: 8080
okapi:
  logs:
    s3:
      region: eu-west-2
      uploadGraceMs: 300000 # 5 min grace period
      bucket: c199eb35-okapi-logs-bucket
      basePrefix: logs
      uploadIntervalMs: 1800000
    dataDir: data-pages
    maxPageBytes: 8388608 # 8 MB by default
    maxDocsPerPage: 1000
    maxPageWindowMs: 3600000 # 1hr
    idxExpiryDuration: 3600000 # 1hr expiry duration for an index file
  swim:
    svcName: okapi-logs
    k8s:
      svcName: okapi-logs
    s3:
      bucket: c199eb35-okapi-logs-bucket