okapi:
  logs:
    dataDir: logs                # Local directory where per-tenant/logStream files are stored
    maxPageBytes: 8388608        # Max serialized page size before flush (bytes). Default 8 MiB
    maxDocsPerPage: 20000        # Max number of log docs per page before flush
    maxPageWindowMs: 120000      # Max time window per page before flush (ms)
    maxActivePages: 10000        # Max in-memory active pages (tenantId+logStream) before backpressure
    bloomFpp: 0.01               # Bloom filter false-positive probability per page
    fsyncOnPageAppend: true      # Force fsync after each page append for durability
    indexFsyncEveryPages: 1      # Fsync index every N page writes (1 = every page)
    s3Bucket: ""                 # If set, S3QueryProcessor will read from this bucket
    s3BasePrefix: logs           # Base prefix in S3 (prefix/tenantId/logStream/{logfile.bin, logfile.idx})

# Notes:
# - Each LogPage is appended to logfile.bin and a fixed-size entry to logfile.idx.
# - Pages contain: tsStart/tsEnd, maxDocId, trigram bitmaps, level bitmaps,
#   a Bloom filter of traceIds, and the list of LogPayloadProto docs.
# - A CRC32 footer is appended at the end of each page.
# - OTLP/HTTP ingest endpoint is exposed at POST /v1/logs with headers:
#     X-Okapi-Tenant-Id, X-Okapi-Log-Stream
